# Generated by Django 4.2.16 on 2024-10-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='description',
            field=models.TextField(default='Description of the project'),
        ),
        migrations.AddField(
            model_name='student',
            name='domain',
            field=models.CharField(default='Domain of the project', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='guide',
            field=models.CharField(default='Guide of the project', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='pname',
            field=models.CharField(default='Name of the project', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='tags',
            field=models.ManyToManyField(to='authentication.tag'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
