# Generated by Django 4.2.16 on 2024-10-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_student_description_student_domain_student_guide_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('sname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('dept', models.CharField(max_length=60)),
                ('academic_year', models.CharField(default='2024-25', max_length=10)),
                ('registered_semester', models.IntegerField(default='1')),
                ('div', models.CharField(max_length=10)),
                ('prn', models.BigIntegerField()),
                ('roll', models.BigIntegerField()),
                ('contact_num', models.FloatField()),
                ('group_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('memName1', models.CharField(max_length=30)),
                ('memPRN1', models.BigIntegerField()),
                ('memRoll1', models.BigIntegerField()),
                ('memName2', models.CharField(max_length=30)),
                ('memPRN2', models.BigIntegerField()),
                ('memRoll2', models.BigIntegerField()),
                ('memName3', models.CharField(max_length=30)),
                ('memPRN3', models.BigIntegerField()),
                ('memRoll3', models.BigIntegerField()),
                ('pname', models.CharField(default='Name of the project', max_length=100)),
                ('guide', models.CharField(default='Guide of the project', max_length=40)),
                ('domain', models.CharField(default='Domain of the project', max_length=50)),
                ('description', models.TextField(default='Description of the project')),
                ('tags', models.ManyToManyField(to='authentication.tag')),
            ],
            options={
                'ordering': ['sname'],
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
