# Generated by Django 4.2.16 on 2024-10-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_group_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='endsem_conducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='midsem_conducted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='submitted_PS',
            field=models.BooleanField(default=False),
        ),
    ]
