# Generated by Django 4.2.16 on 2024-11-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_group_endsem_conducted_group_midsem_conducted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='memEmail1',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='group',
            name='memEmail2',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='group',
            name='memEmail3',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='group',
            name='memName1',
            field=models.CharField(blank=True, default='Name of the member', max_length=30),
        ),
        migrations.AlterField(
            model_name='group',
            name='memName2',
            field=models.CharField(blank=True, default='Name of the member', max_length=30),
        ),
        migrations.AlterField(
            model_name='group',
            name='memName3',
            field=models.CharField(blank=True, default='Name of the member', max_length=30),
        ),
    ]
