# Generated by Django 4.2.16 on 2024-11-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_group_mememail1_group_mememail2_group_mememail3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='memPRN1',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='memPRN2',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='memPRN3',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='memRoll1',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='memRoll2',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='memRoll3',
            field=models.BigIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='group',
            name='tags',
        ),
        migrations.AddField(
            model_name='group',
            name='tags',
            field=models.CharField(default='Tags of the project', max_length=150),
        ),
    ]
