# Generated by Django 4.2.16 on 2024-11-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_group_memprn1_alter_group_memprn2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='PPT',
            field=models.FileField(blank=True, upload_to='PPT/'),
        ),
        migrations.AddField(
            model_name='group',
            name='report',
            field=models.FileField(blank=True, upload_to='Report/'),
        ),
        migrations.AddField(
            model_name='group',
            name='working_model',
            field=models.FileField(blank=True, upload_to='WorkingModel/'),
        ),
    ]
