# Generated by Django 4.2.16 on 2024-11-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_coordinator_alter_group_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='registered_academic_year',
            field=models.CharField(default='2024-25', max_length=30),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='registered_semester',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='registered_academic_year',
            field=models.CharField(default='2024-25', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='registered_semester',
            field=models.IntegerField(default='1'),
        ),
    ]
