# Generated by Django 4.2.16 on 2024-11-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_coordinator_registered_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='joining_date',
            field=models.DateField(default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='qualification',
            field=models.CharField(default='', max_length=150),
        ),
    ]
