# Generated by Django 4.2.16 on 2024-11-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_faculty_joining_date_faculty_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='grade',
            field=models.CharField(default='NA', max_length=2),
        ),
        migrations.AddField(
            model_name='group',
            name='remarks',
            field=models.TextField(blank=True, default='NA'),
        ),
    ]
