# Generated by Django 4.2.16 on 2024-11-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_group_grade_group_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='guide_requests',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='group',
            name='guide_approved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='requested_guide',
            field=models.CharField(default='NA', max_length=40),
        ),
    ]
