# Generated by Django 4.2.16 on 2024-11-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_faculty_guide_requests_group_guide_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='guide_requests',
            new_name='group_requests',
        ),
    ]
