# Generated by Django 4.2.16 on 2024-11-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_rename_guide_requests_faculty_group_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='group',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
