# Generated by Django 4.2.16 on 2024-11-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_group_grade_alter_group_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grade',
            field=models.CharField(default='NA', max_length=2),
        ),
    ]
